####################
###### APLICAÇÃO ######
####################
server:
  port: 8080

####################
###### REDIS ######
####################
redis:
  host: localhost
  port: 6379
  database:
    index: 4
  password: